### ISSUE TITLE
Search creation fails where there are too many filters - Trying to create Searches for P***chy

### ISSUE THREAD

**Issue by anee786** [leandrosardi/blackstack#109]
I tried to create searches for Peachy but got this error:

![image](https://user-images.githubusercontent.com/76562101/104478458-2533fa80-55e4-11eb-900e-4fdc6125bf55.png)

The searches to be created are: 

TSF 2:
https://www.linkedin.com/sales/search/people?doFetchHeroCard=false&geoExcluded=100752109&geoIncluded=101165590&industryIncluded=43%2C46%2C41%2C11%2C45%2C106&logHistory=true&page=1&rsLogId=615428457&searchSessionId=AzOBZ6UJTWysZZn3xSZjOQ%3D%3D&titleExcluded=%2522Independent%2520Financial%2520Advisor%2522%2CFinancial%2520Advisor%2CIFA&titleIncluded=%2522Investment%2520Consultant%2522%2C%2522Financial%2520Consultant%2522%2C%2522Independent%2520Finance%2522%2C%2522Independent%2520Financial%2522%2C%2522Wealth%2520Management%2520Consultant%2522%2C%2522Wealth%2520Management%2520Planner%2522%2C%2522Wealth%2520Management%2520Advisor%2522%2C%2522Investment%2520Planner%2522%2C%2522Investment%2520Advisor%2522%2C%2522Financial%2520Planner%2522&titleTimeScope=PAST_NOT_CURRENT

W***n W***s 1
https://www.linkedin.com/sales/search/people?companyExcluded=Recruitment%2CPump%2CHydraulic%2CFabrications%2CEngineering%2CDevelopments%2CFabrication%2CDemolition%2CGroundwork%2CPumps%2CPower%2CModular%2CManufacturing%2CLaser%2CLift%2CGlazing%2CGroundworks%2CProduction%2CMechanical%2CPlatforms%2CDrilling%2CCasing%2CAsbestos%2CCladding%2CHydraulics%2CRemoval%2CRoofing%2CRestoration%2CSteel%2CStructure%2CStructures%2CWelding&companyIncluded=Projects%2CSystems%2CTraffic%2CGrid%2CInsulation%2CInsulations%2CExternal%2CLighting%2CRail%2CHandrail%2CLifts%2CFoundation%2CFoundations%2CControls%2CEarthing%2CEnergy%2CHVAC%2CInteriors%2CElectricals%2CFramework%2CRevolving%2CElectrical%2CHeating&companySize=B%2CC%2CD&companyTimeScope=CURRENT&doFetchHeroCard=false&geoIncluded=101165590&industryIncluded=48%2C144%2C57%2C135%2C51&logHistory=true&page=1&rsLogId=624649738&searchSessionId=DRTtYFTPTFK%2FwGZyVAC53Q%3D%3D&spellingCorrectionEnabled=false&titleExcluded=Product%2CRecruiter%2CRecruitment%2CRecruit%2CJunior%2CAdvisor%2CRecruiting%2CAssistant%2CIntern%2CStudent&titleIncluded=Owner%2CFounder%2CMD%2CChief%2520Executive%2520Officer%3A8%2CCEO%2CManaging%2520Director%3A16%2C%2522Company%2520Director%2522%2CPartner%2C%2522Commercial%2520Director%2522%2CSales%2520Director%2CBusiness%2520Development%2520Director%2CHead%2520of%2520Sales%2CHead%2520of%2520Business%2520Development&titleTimeScope=CURRENT

**Comment by leandrosardi** [comment]
I wrote a partial solution.

The hash descriptor stored in the field `search.edb_search_configuration` was larger than 4096 chars.
I extended that field to 8000 chars, but I guess that is the max limit I can extend it.

The right solution is to store this hash description into a text file, as we are manging the other field `search.ssm_wizard_configuration`

**Comment by leandrosardi** [comment]
I fixed the glitch.
I created the 2 new searches for the client.
I sent emails to the client with CC to support team.
